import { IconDefinition, library } from '@fortawesome/fontawesome-svg-core';
import { faFacebookF } from '@fortawesome/free-brands-svg-icons';
import {
  faHome,
  faGraduationCap,
  faCheckSquare,
  faCoffee,
  faSlidersH,
  faUniversity,
  faCodeBranch,
  faTimes,
  faSmile,
  faStar,
  faCopy,
  faSearch,
  faCog,
  faQuestionCircle,
  faEnvelope,
  faPhoneAlt,
  faFilePdf,
} from '@fortawesome/free-solid-svg-icons';

library.add(
  faFacebookF,
  faHome,
  faGraduationCap,
  faCheckSquare,
  faCoffee,
  faSlidersH,
  faUniversity,
  faCodeBranch,
  faTimes,
  faSmile,
  faStar,
  faCopy,
  faSearch,
  faCog,
  faQuestionCircle,
  faEnvelope,
  faPhoneAlt,
  faFilePdf,
);
